---
- hosts: webserver
  become: yes
  tasks:
  - name : i want install on only  java ubuntu nodes
    apt: 
     name: "{{installjavapackforubuntu}}"
     state: present
    when: ansible_os_family=="Debian"



 

  - name: i want install on only  java redhat nodes
    yum:
     name: "{{installjavapackforredhat}}"
     state: present
    when: ansible_os_family=="RedHat"

  