---
- hosts: all
  become: yes
  tasks:
  - name : i want install webserver on only ubuntu nodes
    apt: 
     name: apache2
     state: present
    when: ansible_os_family=="Debian"



  - name: i want start webserver on only ubuntu nodes
    service:
     name: apache2
     state: started

  - name: i want install webserver on only redhat nodes
    yum:
     name: httpd
     state: present

  - name: i want start webserver on only redhat nodes
    service:
     name: httpd
     state: started 
