---
- hosts: all
  become: yes
  tasks:
  - name : i want install java on only ubuntu nodes
    apt: 
     name: "{{installjavapackforubuntu}}"
     state: present
    when: ansible_os_family=="Debian"



  - name: i want start java on only ubuntu nodes
    service:
     name: "{{installjavapackforubuntu}}"
     state: started
    when: ansible_os_family=="Debian"

  - name: i want install java on only redhat nodes
    yum:
     name: "{{installjavapackforredhat}}"
     state: present
    when: ansible_os_family=="RedHat"

  - name: i want start java on only redhat nodes
    service:
     name: "{{installjavapackforredhat}}"
     state: started 
    when: ansible_os_family=="RedHat"