---
- hosts: webserver
  become: yes
  tasks:
  - name : i want install webserver on only ubuntu nodes
    apt: 
     name: "{{webserverpackofubutnu}}"
     state: present
    when: ansible_os_family=="Debian"



  - name: i want start webserver on only ubuntu nodes
    service:
     name: "{{webserverpackofubutnu}}"
     state: started
    when: ansible_os_family=="Debian"

  - name: i want install webserver on only redhat nodes
    yum:
     name: "{{webserverpackofredhat}}"
     state: present
    when: ansible_os_family=="RedHat"

  - name: i want start webserver on only redhat nodes
    service:
     name: "{{webserverpackofredhat}}"
     state: started 
    when: ansible_os_family=="RedHat"